### ISSUE TITLE
Generating graph with a function without the major mode

### ISSUE THREAD

**Issue by walseb** [enricoflor/syntree#1] opened 2022-09-24 00:20 UTC
Thank you for making this package! Currently it seems you have to use the major syntree mode to generate the graphs, which makes it difficult to store both the source and the generated graph in a org document. It's useful to keep the original source so that changes can be made without having to manually re-arrange the generated graph. Is there a function I can run to generate the tree graph as a string? That way I could integrate it as a org block.

**Comment by enricoflor** [comment] 2022-09-24 20:48
Hi! So if I understand correctly you'd like the old behaviour back. Right now, `syntree-done` (`C-c C-c` as predefined) puts *both* the source *and* the tree in the kill ring, so that when the syntree buffer is killed, you can yank the tree and also the source (with `yank-pop` or some other command that allows you to yank an entry that is not at the top of the kill-ring).

The main reason I abandoned the old approach instead of keeping it as a way of doing thing beside the new "wysiwyg" approach is that in the old way it wasn't so easy, I find, to customize the output (select a style, change some value of the style etc). But if you think that is not necessary, I could add a command that takes the input from the active region and puts a tree in the kill-ring that is formatted according to `syntree-default-style`.

**Comment by walseb** [comment] 2022-09-25 02:42
I see, that's interesting. Although with that approach you would still have to be careful when replacing the old contents after editing it. Ideally I would just have the source for the tree in a org block. When evaling it using `C-c` it puts the tree in the org output. And when entering the org block using `C-c '` it would start the interactive mode. I think you would get best of both worlds that way. Although that would require some serious development I'm guessing. Maybe you could encode the `syntree-style` inside the tree expression. Or I could just have elisp change it manually while the block is running.

For now I would be happy to just be able to get it running in a src block. I found `syntree--main` which says it accepts strings and outputs a tree, but I haven't been able to get it to work. I just get the error `cond: Malformed style plist: missing :der value`. Maybe I'm doing something wrong.

**Comment by enricoflor** [comment] 2022-09-25 17:36
Ha, now I understand what you mean! For now I have modified `syntree--main` in a9df8652b9ddde6279f6dd8c9a77ed6c947116ce so that it can be used as you intended. Now if `syntree--main` is called outside of syntree-mode it will know how to find the style (the reason why you were getting that mistake is that those variables were set with the major mode). You can also pass the name of the desired style to `syntree--main` as an optional second argument. Let me know if this works for you, and I will think of the org-block integrations then.

**Comment by walseb** [comment] 2022-10-06 17:48
Thank you, I appreciate it! I should have time to check it out next week.

**Comment by walseb** [comment] 2022-10-07 17:11
I have tried it out now. It's perfect with some graphs, for example: 
```lisp
(syntree--main
  (format "%S" '("abc" ("def" "ghi"))))
```
generates
```lisp
abc
 | 
def
 | 
ghi
```
but if I remove that list it gives me errors:
```lisp
(syntree--main
  (format "%S" '("abc" "def" "ghi")))
```
Here is the stack trace:
```lisp
Debugger entered--Lisp error: (wrong-number-of-arguments string-match 4)
  (string-match "[^[:space:]]" only-center nil t)
  (let* ((spaces-list (split-string (string-trim s left-offset right-offset) stem-re t)) (branch (let ((x (let (...) (string-join x ...)))) (concat (syntree--p-get :l-intersection t) x (syntree--p-get :r-intersection t)))) (center (if (characterp (syntree--p-get :branchcenter)) (syntree--p-get :branchcenter) (string-to-char (syntree--p-get :branchcenter)))) (index-center (string-match "[^[:space:]]" only-center nil t)) (branch-list (string-to-list branch))) (let* ((c (nthcdr index-center branch-list))) (setcar c center)) (concat left-offset (apply #'string branch-list) right-offset))
  (cond ((and one-stem-p return-only-center) only-center) (return-only-center (concat left-offset only-center right-offset)) (t (let* ((spaces-list (split-string (string-trim s left-offset right-offset) stem-re t)) (branch (let ((x ...)) (concat (syntree--p-get :l-intersection t) x (syntree--p-get :r-intersection t)))) (center (if (characterp (syntree--p-get :branchcenter)) (syntree--p-get :branchcenter) (string-to-char (syntree--p-get :branchcenter)))) (index-center (string-match "[^[:space:]]" only-center nil t)) (branch-list (string-to-list branch))) (let* ((c (nthcdr index-center branch-list))) (setcar c center)) (concat left-offset (apply #'string branch-list) right-offset))))
  (let* ((stem-re (regexp-quote (syntree--p-get :stem))) (not-stem-re (concat "[^" stem-re "]")) (one-stem-p (eq 1 (length (replace-regexp-in-string not-stem-re "" s)))) (begin-re (concat "^.*" stem-re)) (end-re (concat stem-re ".*$")) (left-offset (replace-regexp-in-string end-re "" s)) (right-offset (replace-regexp-in-string begin-re "" s)) (branch-width (- (length s) (+ (1+ (length left-offset)) (1+ (length right-offset))))) (only-center (concat " " (syntree--fill " " branch-width nil (syntree--p-get :stem)) " "))) (cond ((and one-stem-p return-only-center) only-center) (return-only-center (concat left-offset only-center right-offset)) (t (let* ((spaces-list (split-string (string-trim s left-offset right-offset) stem-re t)) (branch (let (...) (concat ... x ...))) (center (if (characterp ...) (syntree--p-get :branchcenter) (string-to-char ...))) (index-center (string-match "[^[:space:]]" only-center nil t)) (branch-list (string-to-list branch))) (let* ((c (nthcdr index-center branch-list))) (setcar c center)) (concat left-offset (apply #'string branch-list) right-offset)))))
  (if (and (= (length (replace-regexp-in-string " " "" s)) 1) (not return-only-center)) "" (let* ((stem-re (regexp-quote (syntree--p-get :stem))) (not-stem-re (concat "[^" stem-re "]")) (one-stem-p (eq 1 (length (replace-regexp-in-string not-stem-re "" s)))) (begin-re (concat "^.*" stem-re)) (end-re (concat stem-re ".*$")) (left-offset (replace-regexp-in-string end-re "" s)) (right-offset (replace-regexp-in-string begin-re "" s)) (branch-width (- (length s) (+ (1+ (length left-offset)) (1+ (length right-offset))))) (only-center (concat " " (syntree--fill " " branch-width nil (syntree--p-get :stem)) " "))) (cond ((and one-stem-p return-only-center) only-center) (return-only-center (concat left-offset only-center right-offset)) (t (let* ((spaces-list (split-string ... stem-re t)) (branch (let ... ...)) (center (if ... ... ...)) (index-center (string-match "[^[:space:]]" only-center nil t)) (branch-list (string-to-list branch))) (let* ((c ...)) (setcar c center)) (concat left-offset (apply #'string branch-list) right-offset))))))
  syntree--draw-branch(" |    | ")
  (let* ((dir (syntree--p-get :growing)) (complex-node (syntree--concatenate-nodes d)) (raw-subtree (cdr (cdr complex-node))) (raw-stems (car (cdr complex-node))) (stems-tip-str (let ((temp-buffer (generate-new-buffer " *temp*" t))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert raw-stems) (goto-char ...) (let ... ...)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) (branch (syntree--draw-branch raw-stems)) (only-center (syntree--draw-branch raw-stems 'only-center)) (top-long-stem (if (> (syntree--p-get :height) 1) (make-list (syntree--p-get :height) only-center) "")) (label (syntree--split-string 'label nil dir lab branch)) (max-width (apply #'max (mapcar #'length (flatten-tree (list stems-tip-str label branch only-center)))))) (syntree--homogenize-length 'node max-width nil (cl-delete-if #'string-blank-p (flatten-tree (list only-center label top-long-stem branch stems-tip-str raw-subtree)))))
  syntree--gen-subtree("abc" ((3 " | " "def") (3 " | " "ghi")))
  (if (condition-case nil (progn (and (stringp (car l)) (cl-every #'numberp (mapcar #'car (cdr l))) (cl-every #'numberp (mapcar #'car (cdr l))))) (error nil)) (syntree--gen-subtree (car l) (cdr l)) (syntree--merge (cons (car l) (mapcar #'(lambda (x) (if (numberp ...) (identity x) (syntree--merge x))) (cdr l)))))
  syntree--merge(("abc" (3 " | " "def") (3 " | " "ghi")))
  (cdr (syntree--merge (syntree--replace-terminal-strings (read s))))
  (cdr (cdr (syntree--merge (syntree--replace-terminal-strings (read s)))))
  (syntree--horizontalize-text dir (cdr (cdr (syntree--merge (syntree--replace-terminal-strings (read s))))))
  (cl-delete-if #'string-blank-p (syntree--horizontalize-text dir (cdr (cdr (syntree--merge (syntree--replace-terminal-strings (read s)))))))
  (let* ((dir (syntree--p-get :growing)) (raw-output (cl-delete-if #'string-blank-p (syntree--horizontalize-text dir (cdr (cdr (syntree--merge ...))))))) (concat (string-join (syntree--reverse nil raw-output) "\n") "\n"))
  syntree--main("(\"abc\" \"def\" \"ghi\")")
```

Thoughts?

**Comment by enricoflor** [comment] 2022-10-07 20:48
I cannot replicate it! Both generate what's expected for me, but I know what the problem is. In Emacs 29 `string-match` accepts four arguments, but in previous versions only three. I am gonna patch it right away, in both branches.

Thank you for catching the bug!

**Comment by enricoflor** [comment] 2022-10-07 21:04
Done! The fix is in both branches, it should work for you now. Thank you again.

**Comment by enricoflor** [comment] 2022-10-09 00:36
There is now a new branch, org-mode-integration. You should try it: in 06b7d5a4bf6f721dd47cffa3d6f9b3703b1ec9ce I introduced syntree source blocks, which have the behavior you suggested at the beginning. 

Say you have a predefined style called `my-style` and you want to draw a tree according to it but with a value for `:height` of 8 and a value of `:stem` of `"l"`, then you put your input in a block like this and evaluate like you do any other src block.

```
#+begin_src syntree :style 'my-style :height 8 :stem "l"

#+end_src
```

Of course if you don't specify any parameter to the src block the default style will be used.

Let me know what you think!

**Comment by walseb** [comment] 2022-10-09 18:27
That's incredible! It works very well with the graphs I have tried so far. Thank you so much!

**Comment by enricoflor** [comment] 2022-10-09 23:20
Then I'm gonna merge it in main as soon as I update the Info page and the readme!

**Closed as completed by enricoflor** 2022-10-09 23:20 UTC
